# Generated by Django 5.1.1 on 2024-10-08 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "player_stats_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("is_starter", models.BooleanField()),
                ("minutes", models.IntegerField()),
                ("points", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("offensive_rebounds", models.IntegerField()),
                ("defensive_rebounds", models.IntegerField()),
                ("steals", models.IntegerField()),
                ("blocks", models.IntegerField()),
                ("turnovers", models.IntegerField()),
                ("defensive_fouls", models.IntegerField()),
                ("offensive_fouls", models.IntegerField()),
                ("free_throws_made", models.IntegerField()),
                ("free_throws_attempted", models.IntegerField()),
                ("two_pointers_made", models.IntegerField()),
                ("two_pointers_attempted", models.IntegerField()),
                ("three_pointers_made", models.IntegerField()),
                ("three_pointers_attempted", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shot",
            fields=[
                ("shot_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_make", models.BooleanField()),
                ("location_x", models.FloatField()),
                ("location_y", models.FloatField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.player"
                    ),
                ),
                (
                    "player_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.playerstats",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.team"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_games",
                to="app.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_games",
                to="app.team",
            ),
        ),
    ]
