# Generated by Django 5.1.2 on 2024-10-10 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_shot_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="shot",
            name="player",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.player"
            ),
        ),
    ]
