# Generated by Django 5.1.2 on 2024-10-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_shot_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shot",
            name="player",
        ),
    ]
